# Package Overview
package_name: aiap_model

pipeline_name: classification_pipeline
pipeline_save_file: classification_pipeline_output

# model details
model_name: random forest
test_size: 0.2
random_state: 42
cv: 5


# Data Files
#training_data_file: train.csv
#test_data_file: test.csv

# Variables
target: Survive


# Will cause syntax errors as they have spaces
variables_to_rename:
  Ejection Fraction : Ejection_Fraction
  Creatinine phosphokinase: CK
  Blood Pressure: BP

features:
  - Gender
  - Smoke
  - Diabetes
  - Age
  - Ejection_Fraction # renamed
  - Sodium
  - Creatinine
  - Pletelets
  - CK #renamed
  - BP #renamed
  - Hemoglobin
  - Height
  - Weight
  - BMI #new feature


# categorical variables with NA in train set
categorical_vars_with_na_frequent:
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - GarageFinish

categorical_vars_with_na_missing:
  - FireplaceQu

numerical_vars_with_na:
  - LotFrontage

temporal_vars:
  - YearRemodAdd

ref_var: YrSold


# variables to log transform
numericals_log_vars:
  - LotFrontage
  - FirstFlrSF
  - GrLivArea

binarize_vars:
  - ScreenPorch

# variables to map
qual_vars:
  - ExterQual
  - BsmtQual
  - HeatingQC
  - KitchenQual
  - FireplaceQu

exposure_vars:
  - BsmtExposure

finish_vars:
  - BsmtFinType1

garage_vars:
  - GarageFinish

categorical_vars:
  - MSSubClass
  - MSZoning
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - RoofStyle
  - Exterior1st
  - Foundation
  - CentralAir
  - Functional
  - PavedDrive
  - SaleCondition

# variable mappings
qual_mappings:
  Po: 1
  Fa: 2
  TA: 3
  Gd: 4
  Ex: 5
  Missing: 0
  NA: 0

exposure_mappings:
  No: 1
  Mn: 2
  Av: 3
  Gd: 4


finish_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  LwQ: 2
  Rec: 3
  BLQ: 4
  ALQ: 5
  GLQ: 6


garage_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  RFn: 2
  Fin: 3
